### ISSUE TITLE
Redis does not auto-reconnect after restart

### ISSUE THREAD

**Issue by fangniu** [django/channels_redis#20]
**1.versions**
python 2.7.6
Django==1.10.1
channels==0.17.3
asgi-redis==1.0.0
2.configuration
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "asgi_redis.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("10.1.10.75", 6379)],
        },
        "ROUTING": "v1.websocket_routing.channel_routing",
    },
}
**2.run project**
python manage.py runserver 0.0.0.0:8002

2017-01-05 07:51:05,973 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
2017-01-05 07:51:05,973 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
2017-01-05 07:51:05,973 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
2017-01-05 07:51:05,975 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
2017-01-05 07:51:05,976 - INFO - server - Using busy-loop synchronous mode on channel layer
2017-01-05 07:51:05,976 - INFO - server.run - Using busy-loop synchronous mode on channel layer

it is perfect and I can use websocket.

**3. stop redis**
 Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/channels/management/commands/runserver.py", line 155, in run
    worker.run()
  File "/usr/local/lib/python2.7/dist-packages/channels/worker.py", line 88, in run
    channel, content = self.channel_layer.receive_many(channels, block=True)
  File "/usr/local/lib/python2.7/dist-packages/asgiref/base_layer.py", line 43, in receive_many
    return self.receive(channels, block)
  File "/usr/local/lib/python2.7/dist-packages/asgi_redis/core.py", line 152, in receive
    result = connection.blpop(list_names, timeout=self.blpop_timeout)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 1163, in blpop
    return self.execute_command('BLPOP', *keys)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 579, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 577, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 238, in read_response
    response = self._buffer.readline()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 168, in readline
    self._read_from_socket()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 143, in _read_from_socket
    (e.args,))
ConnectionError: Error while reading from socket: (104, 'Connection reset by peer')

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/channels/management/commands/runserver.py", line 155, in run
    worker.run()
  File "/usr/local/lib/python2.7/dist-packages/channels/worker.py", line 88, in run
    channel, content = self.channel_layer.receive_many(channels, block=True)
  File "/usr/local/lib/python2.7/dist-packages/asgiref/base_layer.py", line 43, in receive_many
    return self.receive(channels, block)
  File "/usr/local/lib/python2.7/dist-packages/asgi_redis/core.py", line 152, in receive
    result = connection.blpop(list_names, timeout=self.blpop_timeout)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 1163, in blpop
    return self.execute_command('BLPOP', *keys)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 579, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 577, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 238, in read_response
    response = self._buffer.readline()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 168, in readline
    self._read_from_socket()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 143, in _read_from_socket
    (e.args,))
ConnectionError: Error while reading from socket: (104, 'Connection reset by peer')

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/channels/management/commands/runserver.py", line 155, in run
    worker.run()
  File "/usr/local/lib/python2.7/dist-packages/channels/worker.py", line 88, in run
    channel, content = self.channel_layer.receive_many(channels, block=True)
  File "/usr/local/lib/python2.7/dist-packages/asgiref/base_layer.py", line 43, in receive_many
    return self.receive(channels, block)
  File "/usr/local/lib/python2.7/dist-packages/asgi_redis/core.py", line 152, in receive
    result = connection.blpop(list_names, timeout=self.blpop_timeout)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 1163, in blpop
    return self.execute_command('BLPOP', *keys)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 579, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 577, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 238, in read_response
    response = self._buffer.readline()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 168, in readline
    self._read_from_socket()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 143, in _read_from_socket
    (e.args,))
ConnectionError: Error while reading from socket: (104, 'Connection reset by peer')

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/channels/management/commands/runserver.py", line 155, in run
    worker.run()
  File "/usr/local/lib/python2.7/dist-packages/channels/worker.py", line 88, in run
    channel, content = self.channel_layer.receive_many(channels, block=True)
  File "/usr/local/lib/python2.7/dist-packages/asgiref/base_layer.py", line 43, in receive_many
    return self.receive(channels, block)
  File "/usr/local/lib/python2.7/dist-packages/asgi_redis/core.py", line 152, in receive
    result = connection.blpop(list_names, timeout=self.blpop_timeout)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 1163, in blpop
    return self.execute_command('BLPOP', *keys)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 579, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 577, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 238, in read_response
    response = self._buffer.readline()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 168, in readline
    self._read_from_socket()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 143, in _read_from_socket
    (e.args,))
ConnectionError: Error while reading from socket: (104, 'Connection reset by peer')

**4. recover redis**
Django still can not work after I recovered redis except I restart the django 

So it is there any options i can config ? just like [CONN_MAX_AGE](https://docs.djangoproject.com/en/1.10/ref/settings/#std:setting-CONN_MAX_AGE)
MySQL can be auto-reconnected after I recovered mysql and no restart django  when set CONN_MAX_AGE by None.
Thanks.

**Comment by proofit404** [comment]
According to ASGI specification 

    protocol servers should quit and hard restart if they detect
    that the channel layer has gone down or lost data

So I guess transparent reconnect isn't the case here.

**Comment by fangniu** [comment]
@proofit404 Thank you very much, maybe I need a cluster of redis.

**Comment by andrewgodwin** [comment]
It's meant to reconnect automatically if it was a clean closure (it went down and came up while a request wasn't happening). Did you restart `runworker` or `daphne` to get it working again?

**Comment by proofit404** [comment]
Using one or few redis instances doesn't change picture. Redis cluster solution doesn't supported in the layer implementation.  If you provide few redis instances to the layer, that mean layer will do message distribution itself.  Redis will chose Redis instance for exact message using consistent hash algorithm. If one of redis servers is down, algorithm don't has enough buckets for hash function so it will crash. This is also a reason why you need to shutdown your protocol and application servers before you can add or remove redis instances from this set.

**Comment by fangniu** [comment]
@andrewgodwin yes, it can work by restart runworker . But can django reconnect to redis automatically instead hard restart?

**Comment by andrewgodwin** [comment]
This might not be a bug in the redis layer but rather in Daphne/Channels. When you restart Redis, what are you trying that's failing? Is it HTTP requests? Do they time out, or return an error code?

**Comment by fangniu** [comment]
@andrewgodwin 
```
django urls.py
url(r'^v1/terminal/(?P<host_ip>(.*))$', views.terminal),
```
I use django template return a html which include websocket request. 
when I stopped redis, runworks  error:
`ConnectionError: Error while reading from socket: (104, 'Connection reset by peer')`
`runwork` still the same error  after I restarted the redis(`runwork` can not recovered by itself?).

request again
![image](https://cloud.githubusercontent.com/assets/18655911/21666697/5801c114-d32e-11e6-8745-a328f4a7f3a6.png)

**Comment by andrewgodwin** [comment]
Yes, it might be an issue with either the Redis layer or something in Channels itself then. I'll leave this open for investigation but I won't be able to look into it straight away.

**Comment by eavictor** [comment]
I also bumped into this issue.
Root cause:
asgi_redis does not capture ```redis.exceptions.ConnectionError```

Here is the quick fix.
Only tested on Python 3.6.1
https://github.com/eavictor/asgi_redis/commit/e4854aaac4e491510f6ef90a55f075164645e2c9

@fangniu 
Could you help testing if this patch on Python 2 ?

@andrewgodwin 
Is there any method for asgi_redis sends error message to Daphne while continue retry establish connection to redis ?
e.g. ```yield("Failed to establish connection to redis backend. Auto-reconnect in xx seconds.")```

**Comment by andrewgodwin** [comment]
There's no way to retry "in the background" without shuttling it all off to a separate thread, since it's not running async.

**Comment by eavictor** [comment]
Sorry if I'm causing any misunderstand.
I have tested and confirmed the fix can do auto-reconnect by shutting down and restart redis server.

Here is the test result I got:

1. When redis (or redis cluster) is down, browser will keep loading without showing any error. (because the fix is not async). I only leave the loading page up to 10 minutes.
2. After redis (or redis cluster) is back online, worker will re-connect back within 30 seconds and start serving websocket, all browser loading will start downloading contents and start working.


Thought is very simple:

1. Create a while loop.
2. Create a try-except block for catching ```redis.exceptions.ConnectionError```
3. When connection error is caught, sleep 1~30 seconds and retry. If connection is established, break the while loop.

**Comment by andrewgodwin** [comment]
The new `aioredis` usage in version 2.0 uses its internal pool system and should fix this.

**Comment by jroblak** [comment]
I'm still seeing this issue with `aioredis` 1.2.0 and `channels-redis` 2.1.7. When redis goes down, or restarts, the workers output
```
channels-workers_1   |     return future.result()
channels-workers_1   |   File "/usr/local/lib/python3.6/site-packages/channels/worker.py", line 30, in handle
channels-workers_1   |     [listener.result() for listener in listeners]
channels-workers_1   |   File "/usr/local/lib/python3.6/site-packages/channels/worker.py", line 30, in <listcomp>
channels-workers_1   |     [listener.result() for listener in listeners]
channels-workers_1   |   File "/usr/local/lib/python3.6/site-packages/channels/worker.py", line 37, in listener
channels-workers_1   |     message = await self.channel_layer.receive(channel)
channels-workers_1   |   File "/usr/local/lib/python3.6/site-packages/channels_redis/core.py", line 461, in receive
channels-workers_1   |     return (await self.receive_single(channel))[1]
channels-workers_1   |   File "/usr/local/lib/python3.6/site-packages/channels_redis/core.py", line 484, in receive_single
channels-workers_1   |     index, channel_key, timeout=self.brpop_timeout
channels-workers_1   |   File "/usr/local/lib/python3.6/site-packages/channels_redis/core.py", line 329, in _brpop_with_clean
channels-workers_1   |     return await connection.brpoplpush(channel, backup_queue, timeout=timeout)
channels-workers_1   | aioredis.errors.ConnectionClosedError: Reader at end of file
channels-workers_1   | Task exception was never retrieved
channels-workers_1   | future: <Task finished coro=<Worker.listener() done, defined at /usr/local/lib/python3.6/site-packages/channels/worker.py:32> exception=ConnectionClosedError('Reader at end of file',)>
channels-workers_1   | Traceback (most recent call last):
channels-workers_1   |   File "/usr/local/lib/python3.6/site-packages/channels/worker.py", line 37, in listener
channels-workers_1   |     message = await self.channel_layer.receive(channel)
channels-workers_1   |   File "/usr/local/lib/python3.6/site-packages/channels_redis/core.py", line 461, in receive
channels-workers_1   |     return (await self.receive_single(channel))[1]
channels-workers_1   |   File "/usr/local/lib/python3.6/site-packages/channels_redis/core.py", line 484, in receive_single
channels-workers_1   |     index, channel_key, timeout=self.brpop_timeout
channels-workers_1   |   File "/usr/local/lib/python3.6/site-packages/channels_redis/core.py", line 329, in _brpop_with_clean
channels-workers_1   |     return await connection.brpoplpush(channel, backup_queue, timeout=timeout)
channels-workers_1   | aioredis.errors.ConnectionClosedError: Reader at end of file
channels-workers_1   | Task exception was never retrieved
channels-workers_1   | future: <Task finished coro=<Worker.listener() done, defined at /usr/local/lib/python3.6/site-packages/channels/worker.py:32> exception=ConnectionClosedError('Reader at end of file',)>
channels-workers_1   | Traceback (most recent call last):
channels-workers_1   |   File "/usr/local/lib/python3.6/site-packages/channels/worker.py", line 37, in listener
channels-workers_1   |     message = await self.channel_layer.receive(channel)
channels-workers_1   |   File "/usr/local/lib/python3.6/site-packages/channels_redis/core.py", line 461, in receive
channels-workers_1   |     return (await self.receive_single(channel))[1]
channels-workers_1   |   File "/usr/local/lib/python3.6/site-packages/channels_redis/core.py", line 484, in receive_single
channels-workers_1   |     index, channel_key, timeout=self.brpop_timeout
channels-workers_1   |   File "/usr/local/lib/python3.6/site-packages/channels_redis/core.py", line 329, in _brpop_with_clean
channels-workers_1   |     return await connection.brpoplpush(channel, backup_queue, timeout=timeout)
channels-workers_1   | aioredis.errors.ConnectionClosedError: Reader at end of file
```
And they never reconnect. The only way to get a reconnect is to restart the worker process. Is this intended? The `runworker` command doesn't appear to crash, so our auto-recovery doesn't work either.

**Comment by hu0514** [comment]
I encountered the same problem. When aioredis uses redis to connect, if redis restarts, it will report aioredis.errors.ConnectionClosedError: Reader at end of file error, it seems that aioredis will not reconnect.
