### ISSUE TITLE
After some number of hours I start to see many instances of this exception and my app becomes inaccessible

### ISSUE THREAD

**Issue by beaugunderson** [django/channels_redis#77]
```
2018-02-23 19:09:35,833 WARNING  Application instance <Task pending coro=<AsyncConsumer.__call__() running at /usr/local/lib/python3.6/site-packages/channels/consumer.py:54> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.6/asyncio/futures.py:403, <TaskWakeupMethWrapper object at 0x7fe1ed758708>()]>> for connection <WebSocketProtocol client=['172.17.42.1', 41564] path=b'/frontend/'> took too long to shut down and was killed.
```

**Comment by andrewgodwin** [comment]
That implies that whatever consumer you have is not shutting down cleanly (consumers get a 10 second grace period after the connection they're handling closes to clean up and shut down - if they don't, that warning gets raised). I'd need to see the consumer code for it to help you any further.

**Comment by beaugunderson** [comment]
will work on getting you access to the full consumer code; we have a `disconnect` method and updated it to work with channels2 (`groups` used to be stored in session storage but is now stored on `self`):

```
    def disconnect(self, code):
        if not hasattr(self, 'groups'):
            return

        for group in self.groups:
            PresenceGroup.objects.remove(group, self.channel_name)
```

**Comment by andrewgodwin** [comment]
Ah, you're not raising `StopConsumer` - see here: http://channels.readthedocs.io/en/latest/topics/consumers.html#closing-consumers

**Comment by beaugunderson** [comment]
hero!

consider including that in the example here: http://channels.readthedocs.io/en/latest/topics/consumers.html#websocketconsumer

(my fault for not reading further though)

**Comment by beaugunderson** [comment]
hmm:

```python
    def websocket_disconnect(self, message):
        """
        Called when a WebSocket connection is closed. Base level so you don't
        need to call super() all the time.
        """
        # TODO: group leaving
        self.disconnect(message["code"])
        raise StopConsumer()

    def disconnect(self, code):
        """
        Called when a WebSocket connection is closed.
        """
        pass
```

are there times when `disconnect` is called but not `websocket_disconect`?

**Comment by beaugunderson** [comment]
our consumer is a subclass of `JsonWebsocketConsumer` so would expect StopConsumer() to be raised because of `websocket_disconnect`

**Comment by andrewgodwin** [comment]
Ah, no, that should be fine. I would suggest adding some logging in or overriding it then to see if you can work out why it's not being killed.

**Comment by andrewgodwin** [comment]
It's also possible the changes I just pushed to `asgiref` and `channels` this morning will fix this.

**Comment by beaugunderson** [comment]
@andrewgodwin will check those out!

**Comment by beaugunderson** [comment]
still happening even with the asgiref/channels changes this morning; no other exceptions than the one in the original description

what would be helpful to log for debugging purposes?

**Comment by beaugunderson** [comment]
tried adding logging code and noticed that it wasn't logging when I thought `websocket_disconnect` should be called--did a ton of poking around and finally figured out that something was messed up in the redis DB iself (likely because it was plaintext and then I added symmetric encryption yesterday); a `FLUSHDB` fixed it but I would expect to see errors if it gets into that state :)

**Comment by andrewgodwin** [comment]
Hrm, that is strange. If you can give me some steps to reproduce the weird error we can open an issue to track fixing it.
